# Generated by Django 4.2.16 on 2026-03-01 20:53

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number_id', models.CharField(max_length=100, unique=True)),
                ('api_token', core.fields.EncryptedTextField()),
                ('webhook_verify_token', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='whatsapp_config.whatsappaccount')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='account_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Assignment',
                'verbose_name_plural': 'Account Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'account')},
            },
        ),
    ]
